# Configure main menu and social menu
# icons from https://tabler.io/icons
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
# https://fontawesome.com/icons/television?s=solid icons download here


[[social]]
identifier = "shopping-bag"
name = "AppStore"
url = "https://appstore.cornradio.org/"

[social.params]
icon = "brand-appstore"
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/cornradio"

[social.params]
icon = "brand-github"

[[social]]
identifier = "TV2"
name = "TV"
url = "https://tva.cornradio.org/"

[social.params]
icon = "device-tv-old"

# [[social]]
# identifier = "googleconsole"
# name = "google console"
# url = "https://search.google.com/search-console?resource_id=sc-domain%3Ab.cornradio.org"
# 
# [social.params]
# icon = "timeline"

# [[social]]
# identifier = "brand-google"
# name = "google search site"
# url = "https://www.google.com.hk/search?q=site%3Ab.cornradio.org+a"

# [social.params]
# icon = "brand-google"

[[social]]
identifier = "clock-hour-4"
name = "online clock"
url = "/clock"

[social.params]
icon = "clock-hour-4"

[[social]]
identifier = "rss"
name = "rss"
url = "/index.xml"

[social.params]
icon = "rss"
