# Configure main menu and social menu
# icons from https://tabler.io/icons
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "imageuploader"
name = "image uploader"
url = "https://pasteboard.online/t2.html"

[social.params]
icon = "photo-up"

# [[social]]
# identifier = "googleconsole"
# name = "google console"
# url = "https://search.google.com/search-console?resource_id=sc-domain%3Ab.cornradio.org"
# 
# [social.params]
# icon = "timeline"

[[social]]
identifier = "brand-google"
name = "google search site"
url = "https://www.google.com.hk/search?q=site%3Ab.cornradio.org+a"

[social.params]
icon = "brand-google"

[[social]]
identifier = "clock-hour-4"
name = "online clock"
url = "/clock"

[social.params]
icon = "clock-hour-4"

[[social]]
identifier = "users"
name = "friends"
url = "/p/friends/"

[social.params]
icon = "users"

